print("▬ "*10)
print("Gmail")
print("▬ "*10)
print("Dirreccion de correo electronico: ↓")
correo=input()
print("Contraseña ↓")
contraseña=input()
print("Destinatario del correo: ↓")
correo_receptor=input()
print("Asunto: ↓")
asunto=input()
print("Mensaje: ↓")
mensaje=input()
print("Cantidad de archivos adjuntos: ↓")
cant_adj=int(input())
print("♦"*20)
print("Correo enviado con exito")
print("♦"*20)